notifications:
  email: false
dist: xenial
sudo: required
language: python
python: 2.7
virtualenv:
  system_site_packages: true
addons:
  apt:
    packages:
    - cython
    - python2.7-dev
    - python-chaco
    - python-numpy
    - python-scipy
    - python-wxgtk3.0
    - r-base
    - r-recommended
    - r-cran-lme4
install:
# somehow latest version of numpy is installed
- pip uninstall numpy
# install binary packages
- travis_retry pip install --upgrade pip setuptools wheel
# install all dependencies
- travis_retry pip install simplejson appdirs h5py imageio nptdms pyper
- travis_retry pip install . --no-deps
# install special dependencies
- travis_retry pip install git+git://github.com/ZELLMECHANIK-DRESDEN/dclab.git
- travis_retry pip install git+git://github.com/ZELLMECHANIK-DRESDEN/fcswrite.git
# for tests:
- travis_retry pip install codecov coverage
- pip freeze
script:
- py.test tests/
- coverage run --source=shapeout ./setup.py test
- coverage report -m
after_success:
- codecov

