#!/usr/bin/env python
# -*- coding: utf-8 -*-
from os.path import dirname, realpath
from setuptools import setup, Command
import subprocess
import sys


author = u"Paul Müller"
authors = [author, u"Philipp Rosendahl", u"Maik Herbig"]
name = 'shapeout'
description = 'Data analysis for real-time deformability cytometry (RTDC)'
year = "2015"

long_description = """
This package provides a graphical user interface for the analysis of
cytometry data generated by the RTDC setup of ZellMechanik Dresden.
"""

sys.path.insert(0, realpath(dirname(__file__))+"/"+name)
try:
    from _version import version
except:
    version = "unknown"


class PyTest(Command):
    """ Perform pytests
    """
    user_options = []
    def initialize_options(self):
        pass

    def finalize_options(self):
        pass

    def run(self):
        errno = subprocess.call([sys.executable, 'tests/runtests.py'])
        raise SystemExit(errno)


if __name__ == "__main__":
    setup(
        name=name,
        author=author,
        author_email='paul.mueller at biotec.tu-dresden.de',
        url='https://github.com/ZellMechanik-Dresden/ShapeOut',
        version=version,
        packages=[name],
        package_dir={name: name},
        license="GPL v2",
        description=description,
        long_description=long_description,
        # ShapeOut depends on wxPython and chaco, both of which are not very
        # easy (or impossible) to install from pypi. This list here is just
        # meant as a mental note:
        install_requires=["dclab", "nptdms", "NumPy>=1.7.0", "SciPy>=0.10.0",
                          "statsmodels", "pyper", "wxpython", "chaco",
                          "opencv", "kiwisolver"],
        keywords=["RTDC", "cytometry"],
        classifiers= [
            'Operating System :: OS Independent',
            'Programming Language :: Python :: 2.7',
            'Intended Audience :: Science/Research'
                     ],
        platforms=['ALL'],
        cmdclass = {'test': PyTest,
                    },
        )
